### ISSUE TITLE
How to use this viewer on self trained scenes

### ISSUE THREAD

**Issue by Cholezlh** [julienkay/MobileNeRF-Unity-Viewer#1]
hi,thanks for your work,it's very interesting.but if I have trained a new scene through mobile nerf,how can i import it to use your unity viewer?

**Comment by julienkay** [comment]
Hey! Pretty cool that you've managed to train your own data! It's currently not easy to import your own files, but it should not be too difficult to add that.

I can do it, but I would need some help me with what the output looks like for you. Did you use the [official code](https://github.com/google-research/jax3d/tree/main/jax3d/projects/mobilenerf) to train the MobileNeRF?
Would it be possible for you to send me the assets? (I understand if that's not possible)

Imho the easiest way would be if we agree to put all the assets in a folder and use the same naming convention as on the ones with the demo scenes:
- OBJ files with naming convention: shape_X_Y.obj
- multiple PNG files with naming convention: shapeX.pngfeatZ.png (where Z goes from 0 to 1, so 2 .pngs per shape)
- The weights of the MLP in a file called mlp.json

Then I can implement a menu that lets you choose a folder with source assets, which will automatically import all these.

Let me know if that looks god to you.

**Comment by julienkay** [comment]
I created a new branch [Custom_Data](https://github.com/julienkay/MobileNeRF-Unity-Viewer/tree/Custom_Data).
It has a new menu: *MobileNeRF -> Import from disk*
Feel free to try it and report any issues that you might find.

**Comment by Cholezlh** [comment]
sorry for late relay.this is trained materials through official mobileNeRF, https://drive.google.com/file/d/1R3-vHWrLZEauaX7bGWXwJ4yFLdSRxuME/view?usp=sharing, and the data is from mipnerf, it's a image collection of a room.I will try your new code, thanks very mush.

**Comment by julienkay** [comment]
Hey, thanks for sharing the data. That was really helpful!

It seems there are cases when the individual shapes are not split into several .obj files like in the demo scenes. These shape files then have the naming convention: shapeX.obj (X being the total number of objects specified in the mlp.json)

I just pushed some changes to make this work. After making these, I was able to import your scene in Unity.

Would you mind if I posted a small video about this on Twitter? I can tag you if you want.

**Comment by Cholezlh** [comment]
I use your new pushed code, It worked very good.Thanks for your work again. just feel free to post the video :)
